### ISSUE TITLE
Dynamic Content Styling

### ISSUE THREAD

**Issue by cdiacon** [dotmailer/dotmailer_magentwo#55]
In system configuration the font color options are missing for dynamic content, should be migrated from M1

**Comment by adeelq** [comment]
<img width="1067" alt="screen shot 2015-11-16 at 09 30 25" src="https://cloud.githubusercontent.com/assets/8026815/11177544/8d8a11fe-8c46-11e5-9e05-c9e3a012b83e.png">

New color picker supports jQuery.
